apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: fullstack
  labels:
    role: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend-api
        image: persevcareers6577/perseverance-project:VERSION
        imagePullPolicy: Always
        env:
          - name: DB_CONN_STR
            value: mongodb://mongodb-svc:27017/perseverance?directConnection=true
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        ports:
        - containerPort: 3100
        |# Commenting out the livenessProbe
        # livenessProbe: 
        #   httpGet:
        #     path: /ok
        #     port: 3500
        #   initialDelaySeconds: 2
        #   periodSeconds: 5
        |# Commenting out the readinessProbe
        # readinessProbe:
        #   httpGet:
        #     path: /ok
        #     port: 3500
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   successThreshold: 1
